### ISSUE TITLE
Intellicode is unable to download its model behind proxy

### ISSUE THREAD

**Issue by tamilupk** [MicrosoftDocs/intellicode#4]
Getting error message 'Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.'

While all other VS Code functionalities, extensions are working fine behind the proxy.
![image](https://user-images.githubusercontent.com/29927891/43406327-fbdfbdcc-93e9-11e8-9d74-7cb8f1e497e6.png)

**Comment by vivlimmsft** [comment]
Sorry that you're hitting this issue. Which OS are you using?

**Comment by tamilupk** [comment]
Windows 7.
It takes the system proxy for everything else in VS Code.

**Comment by tamilupk** [comment]
Still didn't work even after setting the environment variable (I am already using the same variable for other applications and it works)
I even tried setting it up in vs code settings and it didn't work.

**Comment by vivlimmsft** [comment]
Can you please send the contents of your `VS IntelliCode` output window?

You can get there by:
1. Opening the Output window if it isn't visible (ctrl+shift+p Toggle Output)
2. Select VS IntelliCode from the combo box
![image](https://user-images.githubusercontent.com/27872315/43419222-31394528-93f5-11e8-9856-36141056934c.png)

**Comment by tamilupk** [comment]
`Acquiring model 'PythonIntellicode-Completions'  with schema version between [1, 1]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=1&maxSchemaVersion=1
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: Error: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:
, (RequestError)
No model available for Python, cannot continue.
`

**Comment by tamilupk** [comment]
Hi vivlimmsft, 
Thanks for your support, I was getting error with the end point _

> 'https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=1&maxSchemaVersion=1'

_
so I did a small hack, I hardcoded Uri in blobStore.js file to 

> 'https://cdsmppestg.blob.core.windows.net/codesmartsfileshares-ppe/completions-180706184920623-1?sv=2017-04-17&sig=PWp0keFi3wgsfV%2BRRCZNxeN7OGZvrZH9ZPxoicdewXU%3D&spr=https&se=2018-07-31T20%3A52%3A10Z&srt=o&ss=b&sp=rl'

This saved my day.

However I expect a permanent solution to this problem.

Thanks

**Comment by vivlimmsft** [comment]
I'm glad you got it working.
We'll look into why we were able to download the blob using the proxy, but not contact the service. This will be fixed next update.

**Comment by quartz010** [comment]
@tamilupk  Hi! Same error here. And I download the  blobStore.js manually. But how to install it?

**Comment by firasrb** [comment]
I have the same problem, but the proposed solution does not work for me. I think in my case it's a certificate problem. This is my output:

`Acquiring model 'PythonIntellicode-Completions'  with schema version between [1, 1]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=1&maxSchemaVersion=1
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: Error: self signed certificate in certificate chain, (RequestError)
No model available for Python, cannot continue.
`

**Comment by markw-t** [comment]
@firasrb , do you by any chance happen to have a web diagnostic/debugging tool such as Fiddler enabled on the machine you are using? It's possible that the self-signed certificates such tools use are not properly recognized by our download infrastructure, causing the problem you are seeing - so if you do have such a tool installed, can you try uninstalling it and see if the problem persists?

Thanks
Mark

**Comment by firasrb** [comment]
@markw-t Thanks for the suggestion, but I don't have any of the those debugging tools on my machine. 

It appears there are problems because I am on a network with a high level of security. There are always trouble whenever the self-signed certificates are involved, such as using pip for python packages. But I've never had any problems with VS Code extensions until now.

I found a workaround by opening VS Code while on a another network. The IntelliCode model was downloaded, and when I went back to the secure network the cached model was used. I guess that means it will not be updated as long as I'm on the secure network, but at least I have something that works for now.

**Comment by jkeech** [comment]
@firasrb, My suspicion is that your network firewall/proxy is performing SSL termination with a self-signed cert (basically man-in-the-middle). If this is true, then you probably have that self signed cert in your trusted root cert store to make most application work in this configuration. For some reason, the library used by the extension to perform the download isn't seeing/honoring that extra cert in your cert store, so it is flagging the cert chain as invalid. 

Can you confirm if you have the self-signed cert in your Trust Root Certification Authorities store? Unfortunately, the error message your reported doesn't list the Issuer of the self-signed cert, but you should be able to see the cert chain in your browser or via curl/openssl.

**Comment by jkeech** [comment]
@tamilupk, it looks like your machine might be configured to use an older TLS/SSL protocol. For security, the IntelliCode service requires TLS 1.2+. It looks like the blob storage url still supports TLS 1.0+, which would explain why that request works for you if you were negotiating with TLS 1.0 or TLS 1.1. Do you know what TLS protocols your machine is using?

**Comment by firasrb** [comment]
@jkeech Yes, I can confirm. I'm on a corporate network with a self signed cert.

**Comment by jkeech** [comment]
Thanks. I'll try to reproduce this and see what we can do to handle this case. Do you normally have to configure other apps to use the self-signed cert manually, or are they automatically able to pick up the cert (e.g from the cert store if you are on Windows)?

**Comment by firasrb** [comment]
@jkeech 
In most cases I don't have to do anything, but occasionally there are some issues.
Examples:
- In order to use conda I have to either disable verification (SSL_NO_VERIFY=1), or I have to add the certificate to cacert.perm in the certifi-package.
- pip only works when specifying the pypi hosts with --trusted-host
- Last time I tried Atom, I had to disable strict-ssl in order to get plugins (never had that problem with VSCode though)
- A few months back we were testing the Azure Machine Learning Workbench. The application would not even start up while on the corporate network.
(No issues with the cases above while on my home network or the corporate guest network)

**Comment by tamilupk** [comment]
@jkeech I could see TLS 1.2 is enabled in my machine, but couldn't verify which version the plugin is using.

**Comment by amalrajks** [comment]
Enabling telemetry fixed this issue for me.

**Comment by svaikstude** [comment]
I get similar error. I am behind a corporate proxy.
HTTP_PROXY and HTTPS_PROXY are configured, strictSsl on VS Code disabled.
I can download the file via browser though.

`Acquiring model 'PythonIntellicode-Completions'  with schema version between [2, 2]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: Error: connect ECONNREFUSED 137.117.101.77:443, (RequestError)
No model available for Python, cannot continue.`

**Comment by Bwin4L** [comment]
I'm also facing this issue at work everytime the extension gets updated because it wipes the model cache.
I'm behind a corporate proxy that also has MITM analysis and certificate injection.

I use the following steps as a temporary workaround until this issue is fixed:

1. Open the Endpoint URL that shows up in the Intellicode log (generally: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2).

2. Download the blob file located at the URL in the blobUri key.

3. Create a folder called IntellicodeModels in C:\Users\<username>\.vscode\extensions\visualstudioexptteam.vscodeintellicode-X.Y.Z\
(**X.Y.Z** being the current Intellicode extension version)

4. In that newly created folder, create a IntellicodeModels.json file and give it the following contents:
`[{"analyzerName":"PythonIntellicode","modelName":"Completions","identity":{"intellicodeModelId":"completions-180906224542806-2","creationTimeUtc":"2018-09-06T22:28:20.9835252+00:00"},"schemaVersion":2,"tags":[],"filePath":"c:\\Users\\<username>\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-X.Y.Z\\IntellicodeModels\\ca784e91-a979-4588-beba-c8e4e64a2ffb","lastAccessTimeUtc":"2018-10-18T08:18:47.119Z"}]`
(replace **completions-180906224542806-2** with the name of the blob you downloaded in step 2, **X.Y.Z** with the version of the extension and **\<username>** with your user name).

5. Copy the blob file downloaded in step 2 and rename it to **ca784e91-a979-4588-beba-c8e4e64a2ffb**

6. If needed, disable and reactivate the Intellicode extension to force a model update.

These steps are for Windows, but I assume they'll work with a couple adjustments regarding paths on Linux and MacOS.

**Comment by svaikstude** [comment]
> I get similar error. I am behind a corporate proxy.
> HTTP_PROXY and HTTPS_PROXY are configured, strictSsl on VS Code disabled.
> I can download the file via browser though.
> 
> `Acquiring model 'PythonIntellicode-Completions' with schema version between [2, 2] Querying IntelliCode service for available models. Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2 Could not reach the IntelliCode service. Checking the local model cache. None of the cached models match. Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: Error: connect ECONNREFUSED 137.117.101.77:443, (RequestError) No model available for Python, cannot continue.`
> 
> For pip I use these settings and it works:
> [http]
> proxy = 10.11.10.1:8080
> sslCAPath = userdir/SSLCert.pem
> 
> If I try to use different network, I get this error:
> 
> `Acquiring model 'PythonIntellicode-Completions' with schema version between [2, 2] Querying IntelliCode service for available models. Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2 Could not reach the IntelliCode service. Checking the local model cache. None of the cached models match. Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: Error: unable to get local issuer certificate, (RequestError) No model available for Python, cannot continue.`

So I managed to find a fix.

Apparently set HTTP_PROXY, was not working for me. I had to add this through Environment Variable  settings:
![image](https://user-images.githubusercontent.com/22123834/47154207-52e94680-d2ea-11e8-9713-ce59142a02d6.png)

And to fix Certificate error I had to add NODE_TLS_REJECT_UNAUTHORIZED=0 variable in the same way.

**Comment by DarthSpock** [comment]
I get this error but I'm behind a corporate VPN that doesn't allow Internet connectivity. It connects only to the corporate intranet. I have to manually disable the VPN in order to receive updates and turn it back on afterwards. The model should be on the local drive and receive updates as needed. Is connectivity to the web really required to use this extension and if so, can you provide a method of downloading the model and send updates through the extension update mechanism?

**Comment by dearcharlie** [comment]
@Bwin4L 
thanks.  it works after using your steps.

**Comment by subramn** [comment]
Not working for me either. is there a workaround

**Comment by gabrielclimb** [comment]
@Bwin4L
It works, but looks i have a new problem

Acquiring model 'PythonIntellicode-Completions'  with schema version between [2, 2]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2
Could not reach the IntelliCode service. Checking the local model cache.
Recent model was found in cache.
vs-intellicode-python was passed a model: {"modelPath":"C:\\Users\\gbarbosasoar\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.0.6\\IntellicodeModels\\ca784e91-a979-4588-beba-c8e4e64a2ffb","schemaVersion":2,"tags":[]}.
**Error while activating Python: {}**

**Comment by jheidlage1222** [comment]
Incase anybody comes across this for java or js/ts, I did this even though our proxies do not use certificates or any other kind of auth and it worked for me. Add environment vars like so.
NODE_TLS_REJECT_UNAUTHORIZED=0 
HTTP_PROXY=http://proxyhost:8080

**Comment by WangCan2049** [comment]
here is my error messages  @vivlimmsft 
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Couldn't reach service Error Message: tunneling socket could not be established, cause=read ECONNRESET, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: tunneling socket could not be established, cause=read ECONNRESET, (Error)
No model available for Python, cannot continue.
```

**Comment by jheidlage1222** [comment]
@vivlimmsft did you try setting the env vars per my comment above?
NODE_TLS_REJECT_UNAUTHORIZED=0
HTTP_PROXY=http://proxyhost:8080

Also, I would unset the https_proxy because the port is the same for both http and https.  Also be sure you are setting environment variables and not settings via settings.json because that won't work either.  Doing those steps caused intellicode to work for both typescript and Java on my work PC.

**Comment by vivlimmsft** [comment]
In the VSCode November 2018 update (1.30) an [experimental setting for enabling network proxy support](https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions) was added, please try that and see if it helps.

If not, I've written some updated steps for manually downloading IntelliCode model blobs. We changed the service API & storage schema when we released version `1.1.0`, so the manual download workaround steps that @Bwin4L wrote no longer apply.

For each language you want to have an IntelliCode model for, click one of the below links and download the blob file located at the URL in the readSasToken key.

* [JavaScript or TypeScript](https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/javascript/intellisense-members/output/latest)
* [Java](https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/java/intellisense-members/output/latest)
* [Python](https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/python/intellisense-members/output/latest)

2. Create a folder called `IntellicodeModels` in `C:\Users\<username>\.vscode\extensions\visualstudioexptteam.vscodeintellicode-<extension-version>`

Replace `<username>` with your username, and `<extension-version>` with the installed IntelliCode extension version.

3. Move all of the blob files you downloaded to the newly created folder.

4. In that newly created folder, create a `IntelliCodeModels-v2.json` file and give it the following contents, removing any language you didn't save the blob for.

```json
[{
    "analyzerName": "intellisense-members",
    "languageName": "javascript",
    "identity": {
        "modelId": "1A3F919CD5B7725108B03C349630A1C82B03",
        "outputId": "manually-downloaded",
        "modifiedTimeUtc": "2018-12-11T20:41:34.686Z"
    },
    "filePath": "c:\\Users\\<username>\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-<extension-version>\\IntellicodeModels\\<blob-filename>",
    "lastAccessTimeUtc": "2019-01-02T17:08:30.930Z"
}, {
    "analyzerName": "intellisense-members",
    "languageName": "java",
    "identity": {
        "modelId": "45788CA1782FEF17F07049DB4764F5647A62",
        "outputId": "manually-downloaded",
        "modifiedTimeUtc": "2018-12-11T20:43:15.144Z"
    },
    "filePath": "c:\\Users\\<username>\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-<extension-version>\\IntellicodeModels\\<blob-filename>",
    "lastAccessTimeUtc": "2018-12-14T18:13:56.047Z"
}, {
    "analyzerName": "intellisense-members",
    "languageName": "python",
    "identity": {
        "modelId": "88630A1B4C077752096ECAA576B92C7D3FA1",
        "outputId": "manually-downloaded",
        "modifiedTimeUtc": "2018-12-11T20:45:03.430Z"
    },
    "filePath": "c:\\Users\\<username>\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-<extension-version>\\IntellicodeModels\\<blob-filename>",
    "lastAccessTimeUtc": "2019-01-02T17:09:02.863Z"
}]
```

Replace `<username>` with your username, `<extension-version>` with the IntelliCode extension version, and `<blob-filename>` with the name of the downloaded blob.

5. Start VSCode, open a source code file in a language you downloaded the blob for, and inspect the `VS IntelliCode` output window.
It should look similar to the below:

```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Couldn't reach service Error Message: getaddrinfo ENOTFOUND prod.intellicode.vsengsaas.visualstudio.com prod.intellicode.vsengsaas.visualstudio.com:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
Recent model was found in cache.
...
```

If you don't see the message "Recent model was found in cache", double check that the json is valid and the blob file exists at the path specified in filePath, then respond with the contents of your `VS IntelliCode` output window.

**Comment by jheidlage1222** [comment]
I am using Version 1.30.1 running in portable mode and I just tried setting http proxy support to override and that caused the intellicode extension to work as expected and I tried it for both typescript and java and that seems to have done the trick.  Belows the screen shot of my http/proxy settings.  Also I have my system proxy settings set via internet options and I have no environment variables defined such as PROXY or HTTP_PROXY either.
![image](https://user-images.githubusercontent.com/23411611/50606480-e9fa7f00-0e93-11e9-8d07-1702c8fcc161.png)

**Comment by sparky2708** [comment]
I am getting:

`Acquiring model 'PythonIntellicode-Completions'  with schema version between [2, 2]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/PythonIntellicode/models/latest?declaredName=Completions&minSchemaVersion=2&maxSchemaVersion=2
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings: Error Message: 404 - "default backend - 404", (StatusCodeError)
No model available for Python, cannot continue.
`

If I try with the browser am also just getting "default backend - 404". What am I doing wrong?

**Comment by jkeech** [comment]
@sparky2708, which version of the IntelliCode extension do you have installed? It looks like you are on an older version of the extension which will no longer be able to download new models from the service. We updated our endpoint to a different url in 1.1.1, and the old url was deprecated and then later removed. Can you try updating to the latest version of the IntelliCode extension (currently at 1.1.2) and see if it fixes the issue?

**Comment by jackyu1978** [comment]
1、you can try to setting the http_proxy and https_proxy environment variable in system to your proxy。
2、when i set the environment, then it can connect my proxy,but it throw a error "unable to verify the first certificate"。 then i modify the file:

**Comment by jkeech** [comment]
@jackyu1978, instead of doing that, can you try the setting the new VS Code setting referenced in https://github.com/MicrosoftDocs/intellicode/issues/4#issuecomment-450946911?

We also have some documentation for enabling the VS Code proxy support at https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code#q-im-having-trouble-getting-intellicode-to-download-models-behind-my-firewall---what-should-i-do.

In general, this feature is simpler than manually editing the intellicode extension files and is the recommended solution.

**Comment by andrenvillela** [comment]
I am running on linux debian.

I did everything as suggested on post of @vivlimmsft commented Jan 2, 2019, I see that I get the downloaded file on the folder /IntellicodeModels but when I start the vscode I get same error as below:

Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C?sv=2018-03-28&sr=b&sig=9EPybtUW%2FD61PPgVBRT41QbKRbu1r5h1uQ5N36IxXFE%3D&se=2019-02-25T19%3A56%3A25Z&sp=r
Download complete.
vs-intellicode-python was passed a model: {"modelPath":"/home/andrevillela/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {"name":"Error","message":"command 'python._loadLanguageServerExtension' not found"}

**Comment by vivlimmsft** [comment]
From that log it looks like the download succeeded, but you're hitting issue #57 .
That should be fixed by our next update. For now you may be able to get past this by reloading the window.

**Comment by andrenvillela** [comment]
same issue after reloading... 

Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/home/andrevillela/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {"name":"Error","message":"command 'python._loadLanguageServerExtension' not found"}

**Comment by Zolerii** [comment]
I was able to download the models after adding `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;` to the IntelliCodeServiceProxy.js file before the API call.

The end result looks like the following.

```typescript
logger_1.Instance.write("Querying IntelliCode service for available models.");
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
let telemetryEvent = telemetry_1.Instance.startTimedEvent(telemetry_1.TelemetryEventNames.INTELLICODE_SERVICE_GET_LATEST_MODEL, true);
telemetryEvent.addProperty(telemetry_1.TelemetryPropertyNames.INTELLICODE_SERVICE_GET_LATEST_MODEL_ANALYZER_NAME, analyzerName);
telemetryEvent.addProperty(telemetry_1.TelemetryPropertyNames.INTELLICODE_SERVICE_GET_LATEST_MODEL_LANGUAGE_NAME, languageName);
var modelApi = new IntelliCodeHttpClient.ModelApi(IntelliCodeServiceProxy.Endpoint);
try {
    var model = yield modelApi.apiV1ModelCommonByLanguageByAnalyzerOutputLatestGet(languageName, analyzerName);
}
catch (err) {
    if (err.response && err.response.statusCode && err.response.body) {
        telemetry_1.Instance.sendFault(telemetry_1.TelemetryEventNames.INTELLICODE_SERVICE_GET_LATEST_MODEL_FAULT, telemetry_1.FaultType.Error, `Server did not return code 200: ${JSON.stringify(err.response)}`, undefined);
        logger_1.Instance.write(`Service responded with status code ${err.response.statusCode}: ${err.response.body}`);
    }
    else {
        logger_1.Instance.write(`Couldn't reach service ${logger_1.Instance.formatErrorForLogging(err)}`);
        telemetry_1.Instance.sendFault(telemetry_1.TelemetryEventNames.INTELLICODE_SERVICE_GET_LATEST_MODEL_FAULT, telemetry_1.FaultType.Error, "Couldn't reach service.", err);
    }
    throw err;
}
```

**Comment by andrenvillela** [comment]
Hi Zolerii, where could I find this IntelliCodeServiceProxy.js so I can change it and check if works...

**Comment by Viou** [comment]
> Hi Zolerii, where could I find this IntelliCodeServiceProxy.js so I can change it and check if works...
@andrenvillela 
for me, it was here:
~/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/out/models

**Comment by jkeech** [comment]
@andrenvillela, we just published version 1.1.4 which should fix the python command error (which is #57).

@Viou, you shouldn't need to edit the js file manually (and with version 1.1.4 it will be harder to do since we are now webpacking our extension for improved performance). Instead, the recommendation is to turn on the VS Code setting for network proxy support: https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions.

**Comment by Zolerii** [comment]
@jkeech I tried that setting before making a manual change to the JavaScript file, but it did not work for me. I still saw the error.

**Comment by andrenvillela** [comment]
> @andrenvillela, we just published version 1.1.4 which should fix the python command error (which is #57).
> 
> @Viou, you shouldn't need to edit the js file manually (and with version 1.1.4 it will be harder to do since we are now webpacking our extension for improved performance). Instead, the recommendation is to turn on the VS Code setting for network proxy support: https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions.

@jkeech I was already set as override then I change to on and IntelliCode is working again... Tks,

**Comment by adolfox** [comment]
I'm still having this issue.  I can get it to work by adding NODE_TLS_REJECT_UNAUTHORIZED=0 to my system environment variables, but the the Python extension throws the following error, 

```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.3.40.nupkg... download failed
Error: Failed with status 403, Forbidden, Uri https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.3.40.nupkg
Starting Jedi Python language engine.
```

**Comment by markw-t** [comment]
@adolfox thanks for the report. The problem you are seeing now is related to the Python LS extension; please can you report it at https://github.com/Microsoft/python-language-server/issues ?

**Comment by luabud** [comment]
@adolfox  I opened an issue on your behalf at https://github.com/microsoft/vscode-python/issues/6696.
Would you be able to provide more information there? The more you can provide, the easier and faster we'll be able to find out what's causing the issue :) thank you!

**Comment by 2234839** [comment]
Recently, I have been reporting an error in vscode 'Couldn't download IntelliCode model. Please check your network connectivity or firewall Settings

Later, I opened the output of vscode and took a closer look because vscode did not have permission to open a model.json file. So use the administrator to open the vscode is ok

**Comment by vivlimmsft** [comment]
Try deleting your `%userprofile%\.vscode\extensions\visualstudioexptteam.vscodeintellicode-*\cache` folder and try again as your regular user.

My guess is that the first time you ran VSCode with IntelliCode installed, VSCode was running as administrator, causing the IntelliCode cache to be created with admin permissions that your user cannot modify.

If that doesn't help, please open a new issue for us to investigate further.

**Comment by snow3461** [comment]
vscode 1.46.1
intellicode 1.2.9

Still having issue downloading intellicode models behind corporate proxy.
In developper console I have this error : unable to get local issuer certificate.

I had to modify intellicode.js as suggested by @Zolerii and added process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0; before the request. It now download without a scratch.

Would be nice to know why I'm facing this issue, and how to workaround it without modifying extension code.

**Comment by meiswjn** [comment]
I am also still facing this issue. Does the extension not respect the proxy settings / truststore?

**Comment by osobeso** [comment]
Hi @meiswjn I'm sorry for the inconvenience.
We've been investigating this issue for some time now, and part of the problem seems to be rooted in Node's structure and how it handles proxy and ssl.
Some users have stated that deactivating ssl check in node (by setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED to 0) has helped them overcome this issue.
We are working on finding the root of the problem, and mitigate it on our side, but in the meantime we only have temporary solutions related to overriding node's default ssl behaviour.

We will keep this thread posted when we find a final solution.
Thanks a lot for the feedback and for using IntelliCode!

**Comment by MattN25** [comment]
FWIW, I solved this on my machine as follows:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

IntelliCode plugin v1.2.11

Corp proxy with auth and SSL/TLS in the middle.

I finally solved the issue by setting NODE_TLS_REJECT_UNAUTHORIZED=0 _on Windows_, not in the WSL host... I think it would help in these discussions if it was made clear which O/S is relevant, as it's very opaque (to me anyway) what portions of VS Code are running on Windows vs. on WSL (Ubuntu in my case).

**Comment by snow3461** [comment]
> I finally solved the issue by setting NODE_TLS_REJECT_UNAUTHORIZED=0 _on Windows_, not in the WSL host...

This is only a workaround, and a very insecure one... I would suggest to revert this once vscode has downloaded intellicode models.

**Comment by k4dmandu** [comment]
> 

I was also looking for a solution because my company's firewall had delayed the download for ages. Here is an update of @Bwin4L solution for VSCode 1.63.2:

1. Download model file from: https://intellicodeprodstorage.blob.core.windows.net/models-prod-output/Output_E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19?skoid=bf9239ea-04ee-49e6-8b41-ee3069ca2a1b&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2022-01-18T09%3A19%3A54Z&ske=2022-01-19T09%3A19%3A54Z&sks=b&skv=2020-02-10&sv=2020-02-10&se=2022-01-18T15%3A08%3A00Z&sr=b&sp=r&sig=iB7SoOALrZ3clDkEXX%2FwhvJuVex%2BhXHGF7WiM4hvfDI%3D
2. remove "Output_" prefix from filename
3. Close VSCode if it's open
4. Copy the downloaded file to C:\Users\username\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.15\cache
5. Create a "models.json" with the following content:
`[{"analyzerName":"intellisense-members-lstm-pylance","languageName":"python","identity":{"modelId":"E61945A9A512ED5E1A3EE3F1A2365B88F8FE","outputId":"E4E9EADA96734F01970E616FAB2FAC19","modifiedTimeUtc":"2020-08-11T14:06:50.811Z"},"filePath":"c:\\Users\\pirmi\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.15\\cache\\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19","lastAccessTimeUtc":"2021-12-19T13:17:46.968Z"}]`
6. Restart VSCode

**Comment by rayate2410** [comment]
Still facing this issue. Running VSCode on Windows 10 and want to open projects via SSH from a SLES VM.
I'm behind a corporate proxy.

Trying to make intellisense work for Java. Failed after trying different approaches:

1. Setting proxy variables on both Windows and Linux.
2. Setting NODE_TLS_REJECT_UNAUTHORIZED=0
3. Downloading model files directly as suggested by @k4dmandu 

Nothing seems to be working so far for me.

**Comment by naks110** [comment]
Started happening to me after updating VS Code to 1.67.2

Proxy settings set to Override by default, just a student writing some Java code.... No proxy or firewall problems anywhere.

Infact rest of the things which use internet in VSCode are working.... I wonder why the issue is going on since 2018... reopen it though

**Comment by fifv** [comment]
> Started happening to me after updating VS Code to 1.67.2 Proxy settings set to Override by default, just a student writing some Java code.... No proxy or firewall problems anywhere.
> 
> Infact rest of the things which use internet in VSCode are working.... I wonder why the issue is going on since 2018... reopen it though.
> 
> Also note I have got Kaspersky AV installed, which adds its own root certificate & inspects traffic.
> 
> Acquiring model 'intellisense-members' for java Querying IntelliCode service for available models. Couldn't reach service Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error) Could not reach the IntelliCode service. Checking the local model cache. None of the cached models match. Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error) No model available for Java, cannot continue.

Using proxy, same thing happens to me when I set proxy setting to 'on'. 
If set to 'Override', then TLS error occurs:
`Couldn't reach service Error Message: Client network socket disconnected before secure TLS connection was established, (Error)`
I can use Intellicode behind proxy before without any error, but it suddenly not works recently. I even tried to clear reinstall vscode and Windows11, try install vscode in windows7 VM, but nothing helps.

**Comment by JAndre761** [comment]
Same happend for me and I also use Kasperky Total Security. Here is the output:
```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
No model v2 available for Python, trying v1.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
No model available for Python, cannot continue.
```
I tried reinstalling but doesn;t fix this issue ;(
